### ISSUE TITLE
Schism utils ignore setup_dir

### ISSUE THREAD

**Issue by seshrajagopal** [CADWRDeltaModeling/azure_dms_batch#2]
When running schism utils, you most likely do not need input atmospheric data to be copied over. If you commented out setup_dir in the yml file used for dmsbatch submit-job it throws this error. 

Traceback (most recent call last):
  File "/home/srajagop/miniconda3/envs/azure/bin/dmsbatch", line 33, in <module>
    sys.exit(load_entry_point('azure-dms-batch', 'console_scripts', 'dmsbatch')())
  File "/home/srajagop/miniconda3/envs/azure/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/srajagop/miniconda3/envs/azure/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/srajagop/miniconda3/envs/azure/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/srajagop/miniconda3/envs/azure/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/srajagop/miniconda3/envs/azure/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/srajagop/miniconda3/envs/azure/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/srajagop/azure_dms_batch/dmsbatch/cli.py", line 30, in submit_schism_job
    schismbatch.submit_schism_job(file, pool_name)
  File "/home/srajagop/azure_dms_batch/dmsbatch/schismbatch.py", line 201, in submit_schism_job
    config_dict['num_scribes'], config_dict['study_dir'], config_dict['setup_dirs'],
KeyError: 'setup_dirs'

**Comment by dwr-psandhu** [comment]
Fixed by https://github.com/CADWRDeltaModeling/azure_dms_batch/commit/08b3009ac074ef927fb3cf516f0b680372af87d7
If setup_dirs are not defined in yaml then there is nothing to do in terms of copying other directories besides the study_dir
